// Booking engine client API — thin, typed wrappers around the two public RPCs
// shipped in migration 20260711193000_phase2_booking_engine.
//
// Security model: the database is the boundary. Both functions are SECURITY
// DEFINER with pinned search_path; anon/authenticated can execute exactly these
// two and read nothing else. All validation, hold logic and race arbitration
// (exclusion constraint, SQLSTATE 23P01) happen inside Postgres — this file
// only shapes inputs and translates machine reasons into human copy.
//
// NOTE: `src/integrations/supabase/types.ts` is regenerated by Lovable Cloud
// sync; until it picks up the new RPCs we type the calls explicitly here.

import { z } from "zod";
import { supabase } from "@/integrations/supabase/client";

// ---------------------------------------------------------------------------
// Input schemas (shared with the wizard forms via @hookform/resolvers/zod)
// ---------------------------------------------------------------------------

export const reserveInputSchema = z.object({
  serviceSlug: z.string().min(1),
  startsAt: z.string().datetime({ offset: true }),
  firstName: z.string().trim().min(1, "First name is required").max(80),
  lastName: z.string().trim().min(1, "Last name is required").max(80),
  email: z.string().trim().email("Enter a valid email address").max(254),
  phone: z
    .string()
    .trim()
    .regex(/^(\+?[0-9 ()-]{7,20})?$/, "Enter a valid phone number")
    .optional()
    .or(z.literal("")),
  marketingConsent: z.boolean().default(false),
  notes: z.string().trim().max(500).optional().or(z.literal("")),
});

export type ReserveInput = z.infer<typeof reserveInputSchema>;

export interface Reservation {
  bookingId: string;
  serviceName: string;
  startsAt: string;
  endsAt: string;
  priceGbp: number;
  depositGbp: number;
  holdExpiresAt: string;
  requiresPatchTest: boolean;
}

// ---------------------------------------------------------------------------
// Machine reason -> human copy (raised as exception messages by the RPCs)
// ---------------------------------------------------------------------------

const REASON_COPY: Record<string, string> = {
  taken: "That time was just taken — please pick another slot.",
  slot_taken: "That time was just taken — please pick another slot.",
  off_grid: "That time isn't on the booking grid — please pick a listed slot.",
  too_soon: "That slot is too close to now — please choose a later time.",
  too_far_ahead: "That date is beyond the current booking window.",
  patch_test_lead:
    "This treatment needs a patch test at least 48 hours beforehand — please choose a later slot.",
  outside_hours: "The studio isn't open at that time.",
  blackout: "The studio is closed at that time.",
  too_many_holds:
    "You have a few reservations awaiting payment already — please complete or let one expire first.",
  invalid_email: "Please enter a valid email address.",
  name_required: "Please enter your first and last name.",
  unknown_service: "That service isn't available to book online.",
};

export class BookingError extends Error {
  constructor(
    public readonly reason: string,
    message: string,
  ) {
    super(message);
    this.name = "BookingError";
  }
}

function toBookingError(raw: { message?: string } | null): BookingError {
  const reason = raw?.message ?? "unknown";
  return new BookingError(
    reason,
    REASON_COPY[reason] ?? "Something went wrong reserving that slot — please try again.",
  );
}

// ---------------------------------------------------------------------------
// RPC wrappers
// ---------------------------------------------------------------------------

/**
 * Available start times (UTC ISO strings) for a service on a local calendar
 * day. DST-safe: slot generation happens in studio-local wall-clock time
 * inside Postgres. Days outside the advance window return an empty list.
 */
export async function getAvailableSlots(
  serviceSlug: string,
  day: string, // "YYYY-MM-DD" — the studio-local calendar day
): Promise<string[]> {
  const { data, error } = await supabase.rpc("get_available_slots" as never, {
    _service_slug: serviceSlug,
    _day: day,
  } as never);

  if (error) throw toBookingError(error);
  const rows = (data ?? []) as Array<{ slot_starts_at: string }>;
  return rows.map((r) => r.slot_starts_at);
}

/**
 * Atomically reserve a slot: upserts the client record, expires stale holds in
 * the window, inserts a pending_payment booking with a hold. On a concurrent
 * race the database exclusion constraint arbitrates and this throws
 * BookingError('slot_taken').
 *
 * The returned hold expires server-side; the deposit checkout (next build
 * step) must complete before `holdExpiresAt` or the slot is released.
 */
export async function reserveSlot(input: ReserveInput): Promise<Reservation> {
  const parsed = reserveInputSchema.parse(input);

  const { data, error } = await supabase.rpc("reserve_slot" as never, {
    _service_slug: parsed.serviceSlug,
    _starts_at: parsed.startsAt,
    _first_name: parsed.firstName,
    _last_name: parsed.lastName,
    _email: parsed.email,
    _phone: parsed.phone || null,
    _marketing_consent: parsed.marketingConsent,
    _notes: parsed.notes || null,
  } as never);

  if (error) throw toBookingError(error);

  const r = data as unknown as {
    booking_id: string;
    service_name: string;
    starts_at: string;
    ends_at: string;
    price_gbp: number;
    deposit_gbp: number;
    hold_expires_at: string;
    requires_patch_test: boolean;
  };

  return {
    bookingId: r.booking_id,
    serviceName: r.service_name,
    startsAt: r.starts_at,
    endsAt: r.ends_at,
    priceGbp: Number(r.price_gbp),
    depositGbp: Number(r.deposit_gbp),
    holdExpiresAt: r.hold_expires_at,
    requiresPatchTest: r.requires_patch_test,
  };
}
